# Generated by Django 5.2 on 2025-04-24 08:48

import django.db.models.deletion
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('admin', 'Admin'), ('employee', 'Employee'), ('freelancer', 'Freelancer')], default='employee', max_length=10)),
                ('role', models.CharField(blank=True, choices=[('writer', 'Writer'), ('producer', 'Producer'), ('compiler', 'Compiler')], default=None, max_length=10, null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/', validators=[users.models.UserProfile.validate_resume_file_type])),
                ('is_approved', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
