# Generated by Django 5.2 on 2025-04-24 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_auto_assign_project_priority_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('Unassigned', 'Unassigned'), ('Assigned', 'Assigned'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Freelancer Selected', 'Freelancer Selected')], default='Unassigned', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='auto_assign',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='FreelancerTaskSelection',
        ),
    ]
