# Generated by Django 5.2 on 2025-04-24 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_project_created_by_alter_assignment_project_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='auto_assign',
        ),
        migrations.RemoveField(
            model_name='project',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='title',
        ),
        migrations.AddField(
            model_name='project',
            name='assigned_compiler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_compiler', to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='project',
            name='assigned_producer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_producer', to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='project',
            name='assigned_writer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_writer', to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='project',
            name='revision_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='script',
            field=models.FileField(blank=True, null=True, upload_to='scripts/'),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('unassigned', 'Unassigned'), ('writing_in_progress', 'Writing in Progress'), ('writing_complete', 'Writing Complete'), ('producing_in_progress', 'Producing in Progress'), ('producing_complete', 'Producing Complete'), ('compiling_in_progress', 'Compiling in Progress'), ('ready', 'Ready'), ('done', 'Done')], default='unassigned', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
        migrations.AddField(
            model_name='project',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('low', 'Low')], default='low', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='topic',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
    ]
