# Generated by Django 5.2 on 2025-04-25 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('unassigned', 'Unassigned'), ('writing_in_progress', 'Writing in Progress'), ('writing_complete', 'Writing Complete'), ('producing_in_progress', 'Producing in Progress'), ('producing_complete', 'Producing Complete'), ('compiling_in_progress', 'Compiling in Progress'), ('done', 'Done')], default='unassigned', max_length=50),
        ),
    ]
