# Generated by Django 5.2 on 2025-04-25 11:00

import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_completion_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='script',
            field=models.FileField(blank=True, null=True, upload_to='scripts/', validators=[projects.models.Project.validate_script_file_type]),
        ),
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/', validators=[projects.models.Project.validate_thumbnail_file_type]),
        ),
        migrations.AlterField(
            model_name='project',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/', validators=[projects.models.Project.validate_video_file_type]),
        ),
    ]
